apiVersion: v2
name: eo-meteringpoints
description: A Helm chart for Kubernetes

type: application
version: 0.1.2

dependencies:
  - name: eo-base-helm-chart
    version: "v0.6.0"
    repository: "https://energinet-datahub.github.io/helm-charts/"
