
deployments:
  - name: api
    replicaCount: 1
    command: "/bin/bash"
    args: "entrypoint_api.sh"
    image:
      repository: projectorigin/ett-meteringpoints
      tag: "latest"
      pullPolicy: IfNotPresent
  - name: consumer
    replicaCount: 1
    command: "/bin/bash"
    args: "entrypoint_consumer.sh"
    image:
      repository: projectorigin/ett-meteringpoints
      tag: "latest"
      pullPolicy: IfNotPresent

service:
  deployment: api
  type: ClusterIP
  port: 80

ingress:
  host: localhost
  path: /api/meteringpoints
  servicePort: 80

