
deployments:
  - name: api
    replicaCount: 1
    command: "/bin/bash"
    args: "entrypoint_api.sh"
    probes: true
    env:
      SQL_URL: postgresql://postgres:1234@ett-postgresql.ett-postgresql.svc.cluster.local:5432/meteringpoints
      SQL_POOL_SIZE: 1
    image:
      repository: projectorigin/ett-meteringpoints
      tag: "latest"
      pullPolicy: IfNotPresent
  - name: consumer
    replicaCount: 1
    command: "/bin/bash"
    args: "entrypoint_consumer.sh"
    probes: false
    env:
      EVENT_BUS_HOST: my-cluster-kafka-plain-bootstrap.ett-kafka.svc.cluster.local
      EVENT_BUS_PORT: 9092
      SQL_URL: postgresql://postgres:1234@ett-postgresql.ett-postgresql.svc.cluster.local:5432/meteringpoints
      SQL_POOL_SIZE: 1
    image:
      repository: projectorigin/ett-meteringpoints
      tag: "latest"
      pullPolicy: IfNotPresent

service:
  deployment: api
  type: ClusterIP
  port: 80

ingress:
  host: localhost
  path: /api/meteringpoints
  servicePort: 80

