eo-base-helm-chart:
  deployments:
    api:
      replicaCount: 1
      command: "/bin/bash"
      args: "entrypoint_api.sh"
      probes: true
      env:
        SQL_URI: postgresql://postgres:1234@eo-postgresql.eo-postgresql.svc.cluster.local:5432/meteringpoints
        SQL_POOL_SIZE: 1
      image:
        repository: ghcr.io/energinet-datahub/eo-meteringpoints-api
        tag: 0.1.5
        pullPolicy: Always

  service:
    deployment: api
    type: ClusterIP
    port: 80

  ingress:
    hosts: []
    paths:
      - /api/meteringpoints
    servicePort: 80
    middlewares:
      - name: eo-auth-service
        namespace:
      - name: meteringpoints-stripprefix

  middleware:
    stripPrefix:
      name: meteringpoints-stripprefix
      prefixes:
        - /api/meteringpoints
