{{- $matchRules := list }}

{{- if .Values.ingress.hosts }}
  {{- $hostsMatchRules := list }}
  {{- range .Values.ingress.hosts }}
    {{- $hostsMatchRules = append $hostsMatchRules (printf "Host(`%s`)" . ) }}
  {{- end}}
  {{- $matchRules = append $matchRules (printf "(%s)" (join " || " $hostsMatchRules)) }}
{{- end}}

{{- if .Values.ingress.paths }}
  {{- $pathsMatchRules := list }}
  {{- range .Values.ingress.paths }}
    {{- $pathsMatchRules = append $pathsMatchRules (printf "PathPrefix(`%s`)" . ) }}
  {{- end}}
  {{- $matchRules = append $matchRules (printf "(%s)" (join " || " $pathsMatchRules)) }}
{{- end}}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "ett-meteringpoints.fullname" . }}
  labels:
    {{- include "ett-meteringpoints.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: {{join " && " $matchRules}}
    kind: Rule
    services:
    - name: {{ include "ett-meteringpoints.fullname" . }}
      port: {{ .Values.ingress.servicePort }}
    middlewares:
      - name: ett-auth-service
      - name: meteringpoints-stripprefix
