# Strip prefix /api/meteringpoints
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: meteringpoints-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /api/meteringpoints
