name: Check Licenses - meteringpoints
on:
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]
    paths:
      - Pipfile
      - Pipfile.lock
      - requirements.txt
      - requirements_test.txt
jobs:
  check-licenses:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check license
      uses: Energinet-DataHub/.github/.github/actions/python-pypi-check-license@feature/add-license-scanner
