name: Lint and Test

env:
  python-version: 3.8

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}

      - name: Install packages
        run: pip install --upgrade setuptools wheel

      - id: cache-pip
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements_test.txt') }}

      - name: Install PIP dependencies
        run: pip install -r requirements_test.txt

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.python-version }}

    - name: Install packages
      run: pip install --upgrade setuptools wheel

    - id: cache-pip
      uses: actions/cache@v1
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements_test.txt') }}

    - name: Analysing the code with flake8
      run: flake8
      working-directory: ./

  unittest:
    name: Unittest
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}

      - name: Install packages
        run: pip install --upgrade setuptools wheel

      - id: cache-pip
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements_test.txt') }}

      - name: Run unittests
        run: pytest tests/unittest/

  integrationtest:
    name: Integrationtest
    needs: unittest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}

      - name: Install packages
        run: pip install --upgrade setuptools wheel

      - id: cache-pip
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements_test.txt') }}

      - name: Run integrationtest
        run: pytest tests/integrationstest/
